package westbank.ws.business.loancontract._2009._11;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-16T23:03:40.422+10:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "urn:westbank:ws:business:LoanContract:2009:11", name = "LoanContract")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LoanContract {

    @WebMethod
    @WebResult(name = "LoanContractResponse", targetNamespace = "urn:westbank:ws:business:LoanContract:2009:11", partName = "response")
    public LoanContractResponse create(
        @WebParam(partName = "request", name = "LoanContractRequest", targetNamespace = "urn:westbank:ws:business:LoanContract:2009:11")
        LoanContractRequest request
    );
}
