package westbank.ws.business.taskdispatch._2009._11;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-19T08:30:31.293+10:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "urn:westbank:ws:business:TaskDispatch:2009:11", name = "TaskDispatch")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TaskDispatch {

    @WebMethod
    @WebResult(name = "TaskDispatchResponse", targetNamespace = "urn:westbank:ws:business:TaskDispatch:2009:11", partName = "response")
    public TaskDispatchResponse dispatch(
        @WebParam(partName = "request", name = "TaskDispatchRequest", targetNamespace = "urn:westbank:ws:business:TaskDispatch:2009:11")
        TaskDispatchRequest request
    );
}
