package com.westbank.ws.business.loanrisk._2009._11;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-20T07:00:44.805+10:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "urn:westbank:ws:business:LoanRisk:2009:11", name = "LoanRisk")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LoanRisk {

    @WebMethod
    @WebResult(name = "LoanRiskResponse", targetNamespace = "urn:westbank:ws:business:LoanRisk:2009:11", partName = "response")
    public LoanRiskResponse evaluate(
        @WebParam(partName = "request", name = "LoanRiskRequest", targetNamespace = "urn:westbank:ws:business:LoanRisk:2009:11")
        LoanRiskRequest request
    );
}
