package westbank.ws.business.bankinformation._2009._11;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-19T08:30:32.169+10:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "urn:westbank:ws:business:BankInformation:2009:11", name = "BankInformation")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BankInformation {

    @WebMethod
    @WebResult(name = "BankInformationResponse", targetNamespace = "urn:westbank:ws:business:BankInformation:2009:11", partName = "response")
    public BankInformationResponse retrieve(
        @WebParam(partName = "request", name = "BankInformationRequest", targetNamespace = "urn:westbank:ws:business:BankInformation:2009:11")
        BankInformationRequest request
    );
}
