package com.westbank.ws.business.creditworthiness._2009._11;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-20T07:00:46.328+10:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "urn:westbank:ws:business:CreditWorthiness:2009:11", name = "CreditWorthiness")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CreditWorthiness {

    @WebMethod
    @WebResult(name = "CreditWorthinessResponse", targetNamespace = "urn:westbank:ws:business:CreditWorthiness:2009:11", partName = "response")
    public CreditWorthinessResponse check(
        @WebParam(partName = "request", name = "CreditWorthinessRequest", targetNamespace = "urn:westbank:ws:business:CreditWorthiness:2009:11")
        CreditWorthinessRequest request
    );
}
