package com.westbank.ws.business.bankprivilege._2018._06;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-10-16T09:57:05.071+11:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "BankPrivilege",
                  targetNamespace = "urn:com:westbank:ws:business:BankPrivilege:2018:06")
public class BankPrivilege_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:com:westbank:ws:business:BankPrivilege:2018:06", "BankPrivilege");
    public final static QName BankPrivilegePort = new QName("urn:com:westbank:ws:business:BankPrivilege:2018:06", "BankPrivilegePort");
    static {
        WSDL_LOCATION = null;
    }

    public BankPrivilege_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BankPrivilege_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankPrivilege_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BankPrivilege_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BankPrivilege_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BankPrivilege_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BankPrivilege
     */
    @WebEndpoint(name = "BankPrivilegePort")
    public BankPrivilege getBankPrivilegePort() {
        return super.getPort(BankPrivilegePort, BankPrivilege.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankPrivilege
     */
    @WebEndpoint(name = "BankPrivilegePort")
    public BankPrivilege getBankPrivilegePort(WebServiceFeature... features) {
        return super.getPort(BankPrivilegePort, BankPrivilege.class, features);
    }

}
