package westbank.ws.business.loansettlement._2009._11;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-16T23:03:40.718+10:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "urn:westbank:ws:business:LoanSettlement:2009:11", name = "LoanSettlement")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LoanSettlement {

    @WebMethod
    @WebResult(name = "LoanSettlementResponse", targetNamespace = "urn:westbank:ws:business:LoanSettlement:2009:11", partName = "response")
    public LoanSettlementResponse start(
        @WebParam(partName = "request", name = "LoanSettlementRequest", targetNamespace = "urn:westbank:ws:business:LoanSettlement:2009:11")
        LoanSettlementRequest request
    );
}
