package westbank.ws.business.bankprivilege._2009._11;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-16T23:03:41.755+10:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "urn:westbank:ws:business:BankPrivilege:2009:11", name = "BankPrivilege")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BankPrivilege {

    @WebMethod
    @WebResult(name = "BankPrivilegeResponse", targetNamespace = "urn:westbank:ws:business:BankPrivilege:2009:11", partName = "response")
    public BankPrivilegeResponse check(
        @WebParam(partName = "request", name = "BankPrivilegeRequest", targetNamespace = "urn:westbank:ws:business:BankPrivilege:2009:11")
        BankPrivilegeRequest request
    );
}
