package com.westbank.ws.business.loancontract._2018._06;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-10-16T13:28:52.274+11:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "urn:com:westbank:ws:business:LoanContract:2018:06", name = "LoanContract")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LoanContract {

    @WebMethod
    @WebResult(name = "LoanContractResponse", targetNamespace = "urn:com:westbank:ws:business:LoanContract:2018:06", partName = "response")
    public LoanContractResponse create(
        @WebParam(partName = "request", name = "LoanContractRequest", targetNamespace = "urn:com:westbank:ws:business:LoanContract:2018:06")
        LoanContractRequest request
    );
}
