package com.westbank.ws.business.loanfile._2018._06;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-10-16T09:57:05.234+11:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "urn:com:westbank:ws:business:LoanFile:2018:06", name = "LoanFile")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LoanFile {

    @WebMethod
    @WebResult(name = "LoanFileResponse", targetNamespace = "urn:com:westbank:ws:business:LoanFile:2018:06", partName = "response")
    public LoanFileResponse update(
        @WebParam(partName = "request", name = "LoanFileRequest", targetNamespace = "urn:com:westbank:ws:business:LoanFile:2018:06")
        LoanFileRequest request
    );
}
