
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package westbank.ws.testmock;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Feb 22 14:47:05 CET 2010
 * Generated source version: 2.2.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "TestMock",
                      portName = "TestMockPort",
                      targetNamespace = "urn:westbank:ws:TestMock",
                      endpointInterface = "westbank.ws.testmock.TestMock")
                      
public class TestMockImpl implements TestMock {

    private static final Logger LOG = Logger.getLogger(TestMockImpl.class.getName());

    /* (non-Javadoc)
     * @see westbank.ws.testmock.TestMock#send(westbank.ws.testmock.TestRequest  request )*
     */
    public void send(TestRequest request) { 
        LOG.info("Got message: " + request);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
