package westbank.ws.testmock;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-19T08:30:31.743+10:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "urn:westbank:ws:TestMock", name = "TestMock")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TestMock {

    @WebMethod
    @Oneway
    public void send(
        @WebParam(partName = "request", name = "TestRequest", targetNamespace = "urn:westbank:ws:TestMock")
        TestRequest request
    );
}
