package westbank.ws.testmock;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-16T23:03:41.597+10:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "TestMock",
                  targetNamespace = "urn:westbank:ws:TestMock")
public class TestMock_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:westbank:ws:TestMock", "TestMock");
    public final static QName TestMockPort = new QName("urn:westbank:ws:TestMock", "TestMockPort");
    static {
        WSDL_LOCATION = null;
    }

    public TestMock_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestMock_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestMock_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TestMock_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TestMock_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TestMock_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TestMock
     */
    @WebEndpoint(name = "TestMockPort")
    public TestMock getTestMockPort() {
        return super.getPort(TestMockPort, TestMock.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestMock
     */
    @WebEndpoint(name = "TestMockPort")
    public TestMock getTestMockPort(WebServiceFeature... features) {
        return super.getPort(TestMockPort, TestMock.class, features);
    }

}
