package com.westbank.ws.business.taskdispatch._2018._06;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-25T11:48:10.586+10:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "TaskDispatch",
                  targetNamespace = "urn:com:westbank:ws:business:TaskDispatch:2018:06")
public class TaskDispatch_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:com:westbank:ws:business:TaskDispatch:2018:06", "TaskDispatch");
    public final static QName TaskDispatchPort = new QName("urn:com:westbank:ws:business:TaskDispatch:2018:06", "TaskDispatchPort");
    static {
        WSDL_LOCATION = null;
    }

    public TaskDispatch_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TaskDispatch_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaskDispatch_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TaskDispatch_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TaskDispatch_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TaskDispatch_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TaskDispatch
     */
    @WebEndpoint(name = "TaskDispatchPort")
    public TaskDispatch getTaskDispatchPort() {
        return super.getPort(TaskDispatchPort, TaskDispatch.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaskDispatch
     */
    @WebEndpoint(name = "TaskDispatchPort")
    public TaskDispatch getTaskDispatchPort(WebServiceFeature... features) {
        return super.getPort(TaskDispatchPort, TaskDispatch.class, features);
    }

}
